// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentalMotorcycle.Data;

#nullable disable

namespace RentalMotorcycle.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RentalMotorcycle")
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentalMotorcycle.Business.Entities.DeliveryMen.DeliveryMan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("cnh");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("Data_nascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identicador");

                    b.Property<string>("Imagem_cnh")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("imagem_cnh");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo_cnh")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("tipo_cnh");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMan", "RentalMotorcycle");
                });

            modelBuilder.Entity("RentalMotorcycle.Business.Entities.Motorcycles.Motorcycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identificador");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("placa");

                    b.HasKey("Id");

                    b.ToTable("motorcycle", "RentalMotorcycle");
                });

            modelBuilder.Entity("RentalMotorcycle.Business.Entities.Rental.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Data_devolucao")
                        .HasColumnType("date")
                        .HasColumnName("data_devolucao");

                    b.Property<DateTime>("Data_inicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime>("Data_previsao_termino")
                        .HasColumnType("date")
                        .HasColumnName("data_previsao");

                    b.Property<DateTime>("Data_termino")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<string>("Entregador_id")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("entregador_id");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Moto_id")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("moto_id");

                    b.Property<int>("Plano")
                        .HasColumnType("int")
                        .HasColumnName("plano");

                    b.HasKey("Id");

                    b.ToTable("rental", "RentalMotorcycle");
                });
#pragma warning restore 612, 618
        }
    }
}
